import { registerSW } from 'virtual:pwa-register';

export interface ServiceWorkerCallbacks {
  /** A new version is waiting; call the returned update function to activate it. */
  onNeedRefresh?: (update: () => Promise<void>) => void;
  /** All assets are cached and the app will now work with no network (NFR-01). */
  onOfflineReady?: () => void;
}

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa. It precaches
 * every build asset, so after the first load the app runs with the network off.
 */
export function registerServiceWorker(callbacks: ServiceWorkerCallbacks = {}): void {
  if (!('serviceWorker' in navigator)) return;
  const updateSW = registerSW({
    immediate: true,
    onNeedRefresh() {
      callbacks.onNeedRefresh?.(() => updateSW(true));
    },
    onOfflineReady() {
      callbacks.onOfflineReady?.();
    },
  });
}
